export const vaultAbi = [
  { type: "function", stateMutability: "view", name: "owner", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", stateMutability: "view", name: "paused", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "subscriptionId", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "outstandingNotional", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "maxOutstandingNotional", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "stepStatus", inputs: [{ type: "bytes32" }], outputs: [{ type: "uint8" }] },
  { type: "function", stateMutability: "nonpayable", name: "approvePool", inputs: [{ type: "address" }, { type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "subscribeAllMarkets", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "setPaused", inputs: [{ type: "bool" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "armStep",
    inputs: [
      { type: "bytes32", name: "stepId" },
      { type: "tuple", name: "s", components: [
        { type: "uint8", name: "status" },
        { type: "bytes32", name: "triggerMarketId" },
        { type: "address", name: "pool" },
        { type: "uint256", name: "price" },
        { type: "uint256", name: "quantity" },
        { type: "uint64", name: "expireNs" },
        { type: "uint8", name: "orderType" },
        { type: "bool", name: "buyYesOnWin0" },
        { type: "uint256", name: "notionalCap" },
        { type: "uint128", name: "orderId" },
        { type: "uint8", name: "winningOutcome" },
      ] },
    ],
    outputs: [] },
  { type: "event", name: "Executed", inputs: [
    { type: "bytes32", name: "stepId", indexed: true },
    { type: "address", name: "pool", indexed: true },
    { type: "uint8", name: "kind" },
    { type: "bool", name: "success" },
    { type: "uint128", name: "orderId" },
    { type: "uint256", name: "notional" },
  ] },
  { type: "event", name: "Triggered", inputs: [
    { type: "bytes32", name: "stepId", indexed: true },
    { type: "bytes32", name: "marketId", indexed: true },
    { type: "uint256", name: "questionId" },
    { type: "bool", name: "voided" },
    { type: "uint8", name: "winningOutcome" },
  ] },
  { type: "event", name: "Skipped", inputs: [
    { type: "bytes32", name: "stepId", indexed: true },
    { type: "bytes32", name: "marketId", indexed: true },
    { type: "string", name: "reason" },
  ] },
] as const;
export const STATUS = ["NONE","ARMED","WAITING","TRIGGERED","EXECUTED","SKIPPED","EXPIRED","CANCELLED"] as const;
